---
- name: install shellhost on penduino experiment
  hosts: penduino
  become: yes
  gather_facts: yes
  
  tasks:

  - name: Include install-shellhost-rpios task
    include: ../tasks/install-shellhost-rpios.yml

  handlers:

  - name: Include shellhost handlers
    include: ../tasks/shellhost-handlers.yml
