---
- name: update sessionhost on penduino experiment
  hosts: penduino
  become: yes
  gather_facts: yes
  
  tasks:

  - name: Include update-sessionhost task
    include: ../tasks/update-sessionhost-rpios.yml

  handlers:

  - name: Include sessionhost handlers
    include: ../tasks/sessionhost-handlers.yml
